"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { BRAND } from "@/brand";

/**
 * Three stacked bars, narrowing upward: the rail, the billing layer, the app.
 * The mark is the architecture, which is also the pitch.
 */
function Mark({ className = "" }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" aria-hidden className={`size-[18px] shrink-0 ${className}`} fill="currentColor">
      <rect x="2" y="15" width="20" height="5" rx="1.6" />
      <rect x="4.5" y="9" width="15" height="5" rx="1.6" opacity="0.6" />
      <rect x="7" y="3" width="10" height="5" rx="1.6" opacity="0.32" />
    </svg>
  );
}

/**
 * Five links, all of which go somewhere that exists.
 *
 * Flat rather than a Product dropdown: a dropdown earns its keep when there
 * are eleven products behind it, and hiding five pages behind a hover target
 * costs discovery for nothing.
 *
 * There is no Pricing entry, deliberately — pricing will run on the product
 * itself, so that page does not exist until it can be generated by the thing
 * it describes. A nav link that 404s would undercut the one page on this site
 * whose whole job is candour.
 */
const LINKS = [
  { href: "/how-it-works", label: "How it works" },
  { href: "/features", label: "Features" },
  { href: "/developers", label: "Developers" },
  { href: "/docs", label: "Docs" },
  { href: "/status", label: "What's built" },
];

export function Nav() {
  const pathname = usePathname();
  const [open, setOpen] = useState(false);

  return (
    <header className="sticky top-0 z-30 border-b border-line/70 bg-paper/85 backdrop-blur">
      <nav className="mx-auto flex h-16 w-full max-w-6xl items-center justify-between px-6">
        <Link href="/" className="inline-flex items-center gap-2.5 font-semibold tracking-tight">
          <Mark />
          {BRAND.name}
        </Link>

        <div className="hidden items-center gap-7 md:flex">
          {LINKS.map((link) => (
            <Link
              key={link.href}
              href={link.href}
              className={`text-sm transition-colors hover:text-ink ${
                pathname === link.href ? "text-ink" : "text-muted"
              }`}
            >
              {link.label}
            </Link>
          ))}
          <a
            href={`${BRAND.appUrl}/register`}
            className="rounded-md bg-ink px-4 py-2 text-sm font-medium text-paper transition-opacity hover:opacity-88"
          >
            Start building
          </a>
        </div>

        <button
          type="button"
          onClick={() => setOpen((value) => !value)}
          aria-expanded={open}
          aria-label={open ? "Close menu" : "Open menu"}
          className="rounded-md border border-line px-3 py-2 md:hidden"
        >
          <svg viewBox="0 0 20 14" aria-hidden className="w-4" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round">
            {open ? (
              <>
                <line x1="3" y1="2" x2="17" y2="12" />
                <line x1="17" y1="2" x2="3" y2="12" />
              </>
            ) : (
              <>
                <line x1="1" y1="2" x2="19" y2="2" />
                <line x1="1" y1="7" x2="19" y2="7" />
                <line x1="1" y1="12" x2="19" y2="12" />
              </>
            )}
          </svg>
        </button>
      </nav>

      {open ? (
        <div className="border-t border-line md:hidden">
          <div className="mx-auto flex w-full max-w-6xl flex-col px-6 py-2">
            {LINKS.map((link) => (
              <Link
                key={link.href}
                href={link.href}
                onClick={() => setOpen(false)}
                className="border-b border-line py-3 text-sm"
              >
                {link.label}
              </Link>
            ))}
            <a
              href={`${BRAND.appUrl}/register`}
              className="my-4 rounded-md bg-ink px-4 py-3 text-center text-sm font-medium text-paper"
            >
              Start building
            </a>
          </div>
        </div>
      ) : null}
    </header>
  );
}

export function Footer() {
  return (
    <footer className="border-t border-line">
      <div className="mx-auto w-full max-w-6xl px-6 py-12">
        <div className="flex flex-col gap-8 sm:flex-row sm:justify-between">
          <div>
            <span className="inline-flex items-center gap-2.5 text-sm font-semibold tracking-tight">
              <Mark />
              {BRAND.legalName}
            </span>
            <p className="mt-3 max-w-xs text-sm leading-relaxed text-muted">{BRAND.tagline}.</p>
          </div>

          <nav className="flex flex-col gap-2.5 text-sm sm:text-right">
            {LINKS.map((link) => (
              <Link key={link.href} href={link.href} className="text-muted transition-colors hover:text-ink">
                {link.label}
              </Link>
            ))}
            <a
              href={`${BRAND.appUrl}/login`}
              className="text-muted transition-colors hover:text-ink"
            >
              Sign in
            </a>
          </nav>
        </div>
      </div>
    </footer>
  );
}
